
package Vistas;

import Colegio.Alumno;
import Colegio.Materia;
import java.util.HashSet;

public class MenuView extends javax.swing.JFrame {
    private HashSet<Alumno> listaAlumnos;
    private HashSet<Materia> listaMaterias;
    
    public MenuView() {
        this.listaMaterias = new HashSet<>();
        this.listaAlumnos = new HashSet<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        agregarAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        inscribirMateria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        salirMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        escritorio.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 255));

        jMenu1.setBackground(new java.awt.Color(255, 204, 204));
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Alumno");

        agregarAlumnos.setBackground(new java.awt.Color(255, 204, 204));
        agregarAlumnos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        agregarAlumnos.setForeground(new java.awt.Color(51, 51, 51));
        agregarAlumnos.setText("Agregar Alumno");
        agregarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(agregarAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(204, 255, 255));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Materia");

        agregarMaterias.setBackground(new java.awt.Color(204, 255, 255));
        agregarMaterias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        agregarMaterias.setForeground(new java.awt.Color(51, 51, 51));
        agregarMaterias.setText("Agregar Materia");
        agregarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(agregarMaterias);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(153, 153, 255));
        jMenu3.setForeground(new java.awt.Color(51, 51, 51));
        jMenu3.setText("Registro");

        inscribirMateria.setBackground(new java.awt.Color(153, 153, 255));
        inscribirMateria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        inscribirMateria.setForeground(new java.awt.Color(51, 51, 51));
        inscribirMateria.setText("Inscribir a Materia");
        inscribirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribirMateriaActionPerformed(evt);
            }
        });
        jMenu3.add(inscribirMateria);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 102, 0));
        jMenu4.setForeground(new java.awt.Color(51, 51, 51));
        jMenu4.setText("Archivo");

        salirMenu.setBackground(new java.awt.Color(255, 0, 51));
        salirMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        salirMenu.setForeground(new java.awt.Color(51, 51, 51));
        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        jMenu4.add(salirMenu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuActionPerformed

    private void agregarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAlumnosActionPerformed
        escritorio.removeAll();
        FormularioDeAlumnosView faView= new FormularioDeAlumnosView(listaAlumnos);
        faView.setVisible(true);
        escritorio.add(faView);
        escritorio.repaint();
    }//GEN-LAST:event_agregarAlumnosActionPerformed

    private void agregarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMateriasActionPerformed
        escritorio.removeAll();
        FormularioDeMateriasView fmView= new FormularioDeMateriasView(listaMaterias); 
        fmView.setVisible(true);
        escritorio.add(fmView);
        escritorio.repaint();
    }//GEN-LAST:event_agregarMateriasActionPerformed

    private void inscribirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribirMateriaActionPerformed

        escritorio.removeAll();
        FormularioDeInscripcionView fiView= new FormularioDeInscripcionView(listaMaterias,listaAlumnos);
        fiView.setVisible(true);
        escritorio.add(fiView);
        escritorio.repaint();
    }//GEN-LAST:event_inscribirMateriaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarAlumnos;
    private javax.swing.JMenuItem agregarMaterias;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem inscribirMateria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem salirMenu;
    // End of variables declaration//GEN-END:variables
}
